# Jekyll configuration

name: 'ashiina on Technology'
description: 'I am a co-founder/CTO of a start-up based in Tokyo, Japan. I will be talking about software techonology in general, but most likely all things tech. '

# url is currently only used only for the RSS feed in feed.xml
url: http://ashiina.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'ashiina'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-58285902-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'ashiinagithubio'
comments: true

permalink: /:year/:month/:title
paginate: 3

gems:
  - jekyll-sitemap

highlighter: rouge

exclude: ['README.md', 'LICENSE']
